-- AlterTable
ALTER TABLE `bidang` MODIFY `idPimpinan` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `jabatan` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `jab` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `img` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `user` MODIFY `nip` VARCHAR(191) NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE `Arsip` (
    `id` VARCHAR(191) NOT NULL,
    `idUser` VARCHAR(191) NOT NULL,
    `kd` INTEGER NOT NULL,
    `uraian` VARCHAR(191) NOT NULL,
    `uraianPoint` VARCHAR(191) NOT NULL,
    `uraianPointC` INTEGER NOT NULL,
    `tgl` VARCHAR(191) NOT NULL,
    `docStatus` VARCHAR(191) NOT NULL,
    `docC` INTEGER NOT NULL,
    `file` VARCHAR(191) NOT NULL,
    `formAs` VARCHAR(191) NOT NULL,
    `formNm` VARCHAR(191) NOT NULL,
    `formVal` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Arsip` ADD CONSTRAINT `Arsip_idUser_fkey` FOREIGN KEY (`idUser`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
